Mrs4s/go-cqhttp

- .github/workflows/ci.yml
- .github/workflows/release.yml
[![CI](https://github.com/mnixry/go-cqhttp/workflows/CI/badge.svg?branch=patch-1)](https://github.com/mnixry/go-cqhttp/actions/runs/193317272)
- Features
1. 在每次push和pull requests时自动编译检查代码错误
2. 编译后能够生成并上传二进制可执行文件
3. 为了安全起见，CI能自动判断是否pull request，仅上传push的构建结果
- Fix
1. 删除了对darwin在ARM上的构建工作流，使得每次Release构建能完全成功执行
> 优化Release工作流，增加CI工作流

- global/config.go
> Enhancement: Add indent to the config.go

- server/http.go
过去的写法会导致字符串 {} 无法发送（因为会被识别成 json）
PS 我不会 go 照着文档改的，如果写错了什么请轻点打我 QAQ
PPS 虽然这么说但是本地我做过测试了应该没问题
> sendXXX api type check

- coolq/cqcode.go
> adjust unescape order

- coolq/cqcode.go
- global/net.go
> feat(music): add netease(163) music for [CQ:music]

- server/websocket.go
> fix(ws): fix concurrent write to ws conn

- coolq/cqcode.go
url="http://web.p.qq.com/qqmpmobile/aio/app.html?id=1101079856"
-> 
url="http://web.p.qq.com/qqmpmobile/aio/app.html?id=100495085"
> Match netease music app id

- coolq/bot.go
- docs/config.md
- global/config.go
> 新增自定义心跳服务间隔时间及开关

- docs/config.md
- global/config.go
- main.go
注意！！
该功能的添加修改了配置文件原有内容
注意前后兼容性问题
新增多次自动重连 #154
> 新增多次自动重连 #154

- coolq/api.go
feat(api): make GetFriendList/GetGroupList/GetGroupMemberList/GetForwardMessage json response data as [] instead of null(empty list)
close #222
> feat(api): make json response [] instead of null(empty list)

- docs/config.md
- global/config.go
- global/ratelimit.go
- go.mod
- go.sum
- main.go
- server/http.go
- server/websocket.go
> feature: _rate_limit

- coolq/api.go
- coolq/cqcode.go
- global/fs.go
- go.mod
- main.go
- server/http.go
- server/websocket.go
[2020-09-22 10:50:46] [ERROR]: 读取服务器地址时出现错误: %vEOF
> feature set_group_portrait

- coolq/api.go
> 添加，好友消息和群消息发送成功日志。可用于正则匹配（历史聊天记录

- coolq/cqcode.go
> Fix empty message segment

- main.go
> 修复机器人已登录但继续尝试登录的缺陷

- coolq/cqcode.go
- main.go
> Fix: set_restart api panic

- coolq/api.go
- go.mod
- go.sum
- server/http.go
- server/websocket.go
(cherry picked from commit 061a230c9fb723ad49e00776fa37aca080973ecd)
> reject_add_request

- coolq/api.go
- server/http.go
- server/websocket.go
> feat get group info no cache

- go.mod
- go.sum
> fix ios record

- server/websocket.go
> websocket not found method fix#508

- coolq/cqcode.go
> fix none msg

- global/codec.go
Attempt to brute force ffmpeg transcoding after failure
> Try force transcoding

- global/filter.go
> fix null json

- main.go
> isFastStart setting appiled to config.hjson gen

- coolq/bot.go
- coolq/cqcode.go
- global/filter.go
> fix cqcode

- .github/ISSUE_TEMPLATE/bug--.md
https://github.com/Mrs4s/go-cqhttp/pull/632#issuecomment-781462052
> 修复新建 Issue 引用问题 #632

- coolq/cqcode.go
- coolq/cqcode_test.go
BenchmarkCQBot_ConvertStringMessage-8             232700              4743 ns/op            2672 B/op         65 allocs/op
BenchmarkCQBot_ConvertStringMessage2-8            752025              1643 ns/op            1376 B/op         17 allocs/op
快，unsafe爽(
> :zap: Speed up cqcode parsing

- server/api.go
- server/http.go
- server/websocket.go
> refactor: 将http，ws的api调用统一

- coolq/api.go
> 限制 handle_quick_op... 的 at_sender 使用场景

- coolq/api.go
> Fix a comment typo

- coolq/api.go
- main.go
- server/daemon.go
> 对cli命令行提供了一些标准化功能 例如 daemon

- coolq/api.go
> fix: quick operation at_sender

- coolq/bot.go
> fix: send temp message

- .gitignore
- .golangci.yml
- global/config.go
- global/config/config.go
- global/terminal/doc.go
- global/terminal/double_click.go
- global/update/update.go
- global/update/update_others.go
- global/update/update_windows.go
- server/api.go
- server/http.go
> enhance linter

- main.go
fix unexpected ReadPassword behavior on linux
> fix Mrs4s#794

- coolq/cqcode.go
> 修复转发信息过期导致panic

- server/http.go
- server/websocket.go
参考:
- https://github.com/howmanybots/onebot/blob/master/v11/specs/communication/authorization.md
- #812 中的提示
> onebot标准中当access token未提供时返回401，不符合时返回403
> 实现 OneBot HTTP/WS 状态码标准

- coolq/api.go
> 添加CQ:at显示检查

- coolq/api.go
- go.mod
- go.sum
- server/api.go
> Add new feature 增加设置在线机型功能

- README.md
向 README 中添加适当的空格以获得更好的观感，参见：[盘古之白](https://github.com/vinta/pangu.js)
> 向 README 中添加适当的空格

- global/signal_unix.go
- global/signal_windows.go
> fix wrong channel closed in SetupMainSignalHandler

- .github/workflows/ci.yml
- .github/workflows/golint.yml
- .github/workflows/suggester.yml
- README.md
- coolq/event.go
- login.go
> 缓存依赖,优化CI编译速度,增加手动触发

- docs/cqhttp.md
> Fix: Typo.

- coolq/bot.go
> Fix: Image mime scan add type webp

- global/config/config.go
> fix: 修复环境变量初始化错误

- main.go
```diff
go-cqhttp service
version: v1.0.0-beta6
Usage:
server [OPTIONS]
Options:
-D    debug mode
-c string
-         configuration filename default is config.hjson (default "pwd/config.yml")
+         configuration filename (default "pwd/config.yml")
-d    running as a daemon
-h    this help
-w string
cover the working directory
```
> enhance help

- go.mod
- go.sum
- main.go
在 win / unix 系统下将 key 参数替换为`*`
> feat: hide key in command line.

- Dockerfile
https://github.com/Mrs4s/go-cqhttp/issues/1084
> add `ffmpeg` into Dockerfile

- docs/config.md
> Update config.yml template

- coolq/api.go
- go.mod
- go.sum
- modules/api/api.go
第一次写go……照虎画猫了属于是
如果有哪里写的不规范的希望能多多指教
> feat: guild role API

- .github/workflows/build_docker_image.yml
> ci(package): remove useless nightly package

- .github/ISSUE_TEMPLATE/bug-report.yaml
> 更新 bug 模板版本信息

- coolq/api.go
> fix: uploadForwardElement upload image error

- coolq/cqcode.go
> fix: examine errors that have been ignored in the 'CQ:at' parser

- coolq/api.go
- modules/api/api.go
支持设置 QQ 个人资料
`set_qq_profile`
可选参数：nickname、company、email、college、personalNote
本地测试用例通过，响应示例：
Link #1348
> feat: set qq profile

- .github/ISSUE_TEMPLATE/bug-report.yaml
- global/codec.go
Ref: https://trac.ffmpeg.org/wiki/Create%20a%20thumbnail%20image%20every%20X%20seconds%20of%20the%20video  
Force a screenshot of the 0th second of the video
> 👽️ Update ffrmpeg screenshot command

- coolq/api.go
- modules/api/api.go
Added two apis: send_forward_msg & send_private_forward_msg
> feat: send forward msg to private

- coolq/cqcode.go
> feat: supported finger-guessing message

- coolq/api.go
- coolq/converter.go
- coolq/cqcode.go
- coolq/cqcode/element.go
- coolq/event.go
顺便换了几个 strings.Builder 到 binary.NewWriterF
> revert: re-include url in message

- coolq/api.go
> Fix forward msg

- docs/cqhttp.md
用upload_group_file上传私聊文件?不应该是upload_private_file吗qwq
> 文档修正[使用upload_private_file上传私聊文件

- coolq/api.go
- docs/cqhttp.md
- go.mod
- go.sum
- modules/api/api.go
> feat: del group notice

- coolq/cqcode.go
caused by GroupID in ReplyElement when reply in private session
> Fix private replyId

- cmd/gocq/main.go
- internal/base/flag.go
- server/daemon.go
> fix: more compatible behavior and some fix for deamon pid

- global/terminal/double_click_windows.go
This feature need testing on older system.
Before:
After:
Signed-off-by: Ink33 <Ink33@smlk.org>
> feat: msgbox support high dpi

- cmd/gocq/main.go
> fix: daemon mode

- Dockerfile
- docker-entrypoint.sh
> docker: use su-exec to run cqhttp as a non-root user

- coolq/event.go
- global/quote.go
> groupJoinReqEvent添加字段 invitor_id

- go.mod
- go.sum
This PR update isatty to 1.1.1.
See comment for b981b45245b46923d7e12d489429b849d4082480.
> chore: update isatty

- coolq/api.go
- coolq/cqcode/all_test.go
- coolq/cqcode/element.go
- go.mod
- go.sum
- modules/api/api.go
- server/http.go
增加群组匿名开关
relate to [docs.go-cqhttp.org/api/#%E7%BE%A4%E7%BB%84%E8%AE%BE%E7%BD%AE%E7%AE%A1%E7%90%86%E5%91%98](https://docs.go-cqhttp.org/api/#%E7%BE%A4%E7%BB%84%E8%AE%BE%E7%BD%AE%E7%AE%A1%E7%90%86%E5%91%98)
> Support API set_group_anonymous

- .github/workflows/release.yml
by replacing actions/checkout with git clone command.
> fix(goreleaser): git rev-list --count master

- coolq/cqcode.go
> Fix #2226  尝试将 replyID 识别成正确的发送者ID

- coolq/api.go
> 尝试使 get_msg 获取消息中的回复信息

- coolq/api.go
- 修复获取群荣誉列表群聊之火键名错误问题
- 修复获取版本信息，错误的go-cqhttp字段
> fix: 修复和文档不一致的数据

- coolq/api.go
撤销 #2207
才发现这么做会导致日志里出现
[WARNING]: 警告: 一条信息只能包含一个 Reply 元素.
> Revert #2207

- cmd/gocq/qsign.go
Add missing wg.Wait()
Fixes: fd6ef4a2b8ed ("optimize(qisgn): async operations")
> !fixup: optimize(qisgn): async operations

- coolq/cqcode.go
- coolq/event.go
> 尝试实现 #2421
