server/http.go
修复原先http api下对`Get`和`Post`请求都同时进行鉴权的bug
=> Fix permission check of http.go

coolq/cqcode.go
否则 `[]` 会变成 `&amp;#91;&amp;#93;`
=> & escape should come first

coolq/cqcode.go
参见 [消息格式](https://github.com/cqhttp/cqhttp-protocol/blob/master/legacy/Message.md#%E6%A0%BC%E5%BC%8F)
> 由于消息段不再将纯文本和多媒体内容放在一起，也就意味着任意一个字段的值都是真实值，而不再需要转义。
=> 移除上报消息为array时的文本转义

coolq/bot.go, coolq/event.go, global/fs.go, main.go
1967e687af14466d6654e61fa214acb96c95a83a 里改了一部分权限。
其实该 commit 改后，确实比改前的表现好多了（改前允许系统里所有其他用户和组进入 go-cqhttp 建立的文件夹随意读写其中文件，却唯独不允许 go-cqhttp 本身读写…… 为什么要这样设权限……）
但这次给了过多权限，存在安全隐患（给了系统中所有用户和组将 go-cqhttp 接收到的文件当作可执行程序执行的权限，存在构造恶意 shell code 的风险）。
`os.ModePerm` 是和 `os.ModeType` 对偶的、系统中所有权限的总和。这两个常数存在的目的是以 `FileMode & os.ModeType` 或 `FileMode & os.ModePerm` 的方式来将 FileMode 劈成两个部分分别处理，并不是让用户选为新建文件的默认值。正如不应该把文件的类型设为 `os.ModeType` 一样（一个既是文件夹，又是普通文件，又是块设备，又是文本设备，又是管道，又是软链接的奇怪东西……），通常也不应该把文件的权限设为 `os.ModePerm`。
----
另一处修改是关于 `time.Duration` 打印的。
`time.Duration` 虽然底层是 `type Duration int64` 的纳秒数，但是[该类型实现了 `Stringer` 接口](https://golang.org/pkg/time/#Duration.String)，`fmt.Printf()` 会优先用该接口格式化。由于 `time.Duration / time.Duration` 的类型是 `time.Duration`，如果消息处理的用时是 `12.34s`，当前实现打印的结果将是 `12ns秒`。故将其修正为打印`12.34s`。
=> remove os.ModePerm

global/fs.go
试了一下，`data/voices` 中接收到的文件虽然扩展名是 amr，但实际格式是 silk。
这里对文件头做了限制发不出去，放开此限制后可以发送出去。
=> support silk audio

coolq/api.go
修改了与标准不符的字段。
https://github.com/howmanybots/onebot/blob/master/v11/specs/api/public.md#send_msg-%E5%8F%91%E9%80%81%E6%B6%88%E6%81%AF
=> fix get_msg response payload

coolq/api.go
https://github.com/howmanybots/onebot/blob/master/v11/specs/api/public.md#get_status-%E8%8E%B7%E5%8F%96%E8%BF%90%E8%A1%8C%E7%8A%B6%E6%80%81
good：状态符合预期，意味着各模块正常运行、功能正常，且 QQ 在线
=> get_status: fix inconsistant bahavior compared to onebot spec

Dockerfile
1. 根据 [Docker文档](https://docs.docker.com/engine/reference/builder/#workdir) 里的描述，`WORKDIR` 指令在目录不存在时会自动创建，因此没必要在 `WORKDIR /build` 之前执行 `mkdir /build`
2. 执行 bash 脚本之前最好加上 `set -ex`，因为脚本执行过程中可能会出错，`-e` 在出错时会立即退出， `-x` 会打印出错误调用栈
[GNU手册](https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html)
3. `docker build . -t mrs4s/go-cqhttp:v0.x` 创建镜像没啥问题
=> remove mkdir, add set -ex

server/apiAdmin.go
在账号冻结断线后，会无限重连
根据重连日志分析，发现每次重连失败后，都会新增一个goroutine参与重连
应该是MiraiGo网络层的bug
=> fix reconnect

coolq/api.go
Fix https://github.com/Mrs4s/go-cqhttp/issues/542
理论上这个是正常支持的
=> Make send_group_forward_msg can use on get_msg

server/apiAdmin.go
这个提示应该没啥用 新账号登录的时候需要验证 返回的err是nil会导致null pointer dereference
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xc7069c]
goroutine 1 [running]:
github.com/Mrs4s/go-cqhttp/server.(*webServer).logincore(0x1755d80, 0x0)
C:/Users/Tony/Downloads/go-cqhttp-dev/server/apiAdmin.go:153 +0x1c1c
github.com/Mrs4s/go-cqhttp/server.(*webServer).Dologin(0x1755d80)
C:/Users/Tony/Downloads/go-cqhttp-dev/server/apiAdmin.go:320 +0x57
github.com/Mrs4s/go-cqhttp/server.(*webServer).Run(0x1755d80, 0xc000542820, 0xe, 0xc00041f400, 0x2)
C:/Users/Tony/Downloads/go-cqhttp-dev/server/apiAdmin.go:114 +0x229
main.main()
C:/Users/Tony/Downloads/go-cqhttp-dev/main.go:281 +0xac3
```
=> 去掉无用的登录错误提示

.github/workflows/ci.yml, .github/workflows/release.yml, coolq/cqcode.go
BenchmarkCQBot_ConvertStringMessage-8 232700 4743 ns/op 2672 B/op 65 allocs/op
BenchmarkCQBot_ConvertStringMessage2-8 752025 1643 ns/op 1376 B/op 17 allocs/op
经过小优化后:
BenchmarkCQBot_ConvertStringMessage-8             963939              1205 ns/op             368 B/op         11 allocs/op
ci中使用-trimpath，能减小1k的体积
=> Accelerate cqcode again！

server/api.go
试图通过 get_group_info 获取某个群的信息却返回了机器人所加群的列表
=> Repair: 获取群信息却返回了群列表

coolq/api.go, coolq/bot.go, coolq/cqcode.go, coolq/event.go, docs/cqhttp.md
> Commit里面的信息已经进行分类，方便查看
- `SendGroupForwardMessage` 添加发送失败Handler
- 禁言逻辑修复, 可以进行30(整)天的禁言
- 添加无法撤回临时信息Handling
- 临时会话中的变量改名 (code -> groupId)
- 临时会话发送与接收信息入库 (唯独没法加InternalId)
- 警告信息添加空格 (见cqcode.go)
- 为自定义reply添加seq选项以加真实性
- 更新文档: 添加seq说明, 缩短某个网址, 添加某个`CQcode`定义的导向
- 修复好友被删除后的处理 #374
=> 修复bug&更正代码

coolq/api.go
> This is a Cherry-pick of #728
Closes #725, #727, #711
WIP:
Commit message:
为getGroupInfo添加更多字段
CQGetGroupInfo 逻辑重新排列
noCache 终于可以用了 (好耶!)
没有更新文档 (本身就没关于get_group_info的说明)
注: 文档更新会移到go-cqhttp-docs的repo进行
=> get_group_info 添加更多字段

coolq/api.go, coolq/cqcode.go, global/config/config.go, global/config/default_config.yml
更改:
- 发送: 自定义reply可以用id了
- 发送: CQ:at 中的QQ如果不存在会使用name的field作为补偿
添加可选选项:
- 接收: 添加延申reply信息
- 删除回复消息中重复的艾特 (Closes #764)
=> at, reply 添加更多细节

Dockerfile
io.ReadAll in global/update/update_others.go requiring go version >= 1.16, upgrade builder version in dockerfile to fix docker image build.
=> chore(dep): Upgrade go from 1.15.5 to 1.16 in dockerfile.

global/config/config.go
配置文件不存在时config.Get()返回非空指针, 导致无法创建默认配置文件
=> fix config.Get()

coolq/bot.go
gzip 消耗过多内存
经测试，仅使用leveldb中自带的snappy压缩可以得到体积占用更小
=> breaking change: write leveldb without gzip compress

README.md
根据标准将 WebSocket 和 OneBot 中间的字母改为大写。
=> 修改 README 中的几处拼写细节

global/signal.go, global/signal_unix.go, global/signal_windows.go, go.mod, go.sum, main.go
使用方法:
```
*unix: kill -USR1 <gocq_pid>
windows: echo dumpstack >\\.\pipe\go-cqhttp-<pid>
```
stackdump将直接以`<exec_name>.<pid>.stacks.<timestamp>.log`的文件名保存在当前工作目录下
Testcase
```
C:\Users\Asuka>echo "dumpstack" >\\.\pipe\go-cqhttp-16496
The process tried to write to a nonexistent pipe.
C:\Users\Asuka>echo dumpstack >\\.\pipe\go-cqhttp-16496
The process tried to write to a nonexistent pipe.
C:\Users\Asuka>echo dumpstack > \\.\pipe\go-cqhttp-16496
The process tried to write to a nonexistent pipe.
```
```
time="2021-06-26T14:17:09+08:00" level=warning msg="named pipe 读取到未知指令: \"\\\"dumpstac\""
time="2021-06-26T14:17:28+08:00" level=info msg="开始 dump 当前 goroutine stack 信息"
time="2021-06-26T14:17:28+08:00" level=info msg="stackdump 已保存至 ___go_build_test_go.exe.16496.stacks.1624688248.log" …
```
=> 添加无需额外配置直接打印stack的功能

coolq/bot.go
在用 `get_group_msg_history` 的时候发现的
每次转换讯息都只用当前时间, 这样会严重扰乱其它程序对信息的 `Timestamp` 进行储存的依赖
gocq 主程序却把正常的 Timestamp 储存进 leveldb 里面, 让人感觉到有一点偏心
以上是废话, 简单一句:
解决程序错误返回群信息的 `Timestamp`
/cc @wdvxdr1123
=> 修改错误的 `Timestamp`

server/http.go
beta7 版本时，HTTP POST 的数据内容类型为 [json](https://github.com/Mrs4s/go-cqhttp/blob/60d5f4d3869667a4771189c2e6a40720c0a67bbd/server/http.go#L223)
=> 修正 HTTP POST 内容类型为 json

coolq/api.go
`path.Ext()` 的返回值里面已经有点了，现在我目录里缓存了好多 `*.image..jpg` 的文件…
=> Fix image..jpg

modules/config/config.go
由于`os.ExpandEnv`会解析`$`且无法转义，导致配置文件中包含`$`的值无法正常被解析
使用regex写的一个expand替换掉`os.ExpandEnv`
=> fix(expand env): change os.ExpandEnv to regex

server/http.go
支持设置 HTTP POST 上报 Event 最大重试次数和重试间隔时间，
顺带解决了先前重试被迫停止后空指针的问题
此两配置是可选的，若不填则使用默认配置（最大次数：3，重试间隔：1.5s）
参考配置文件
```yaml
post:
- url: 'https://114.14.191.9:810/1145141919810'
secret: '233'
max-retries: 10 # 0 表示禁用重试
retries-interval: 1000 # 单位毫秒，0 表示立即重连
```
测试
```
[2021-12-24 17:25:31] [WARNING]: 上报 Event 数据到 *** 失败: Post "***": dial tcp ***: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试
[2021-12-24 17:25:33] [WARNING]: 上报 Event 数据到 *** 失败: Post "***": dial tcp ***: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试
[2021-12-24 17:25:36] [WARNING]: 上报 Event 数据到 *** 失败: Post "***": dial tcp ***: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 …
```
=> feat: support set max retries and retries interval (close #1252)

coolq/api.go, go.mod, go.sum, modules/api/api.go
```json
{
"data": [
{
"sender_id": 114514,
"publish_time": 1919810,
"message": {
"text": "我永远喜欢樱花千代",
"images": [
{
"height": "342",
"width": "314",
"id": "SOREzKY8sB3N6vvVos6WwiaWgsEicCnrGuH1ZmhC3P8QA"
}
]
}
},
{
"sender_id": 114514,
"publish_time": 1919810,
"message": {
"text": "test",
"images": []
}
}
],
"retcode": 0,
"status": "ok"
}
```
close #493
=> feat: support get group notice #493

cmd/gocq/main.go
当权限644时候，data文件夹会由于没有执行权限而无法创建后续的图片...等一系列文件夹。
=> fix: data文件夹权限问题

coolq/cqcode.go
NumberLong对应的类型是int64，断言为uint32触发panic
在此文件内其它有类型断言的地方也可能有类似的问题
=> fix a bug 使用mongodb时 image的 subtype会被存储为NumberLong类型

coolq/cqcode.go
r.Sender == source.PrimaryID 为用户回复用户发送消息的情况
r.GroupID == source.PrimaryID 为用户回复 bot 的情况
直接回复的时候 id 就为 r.GroupID
=> fix: #1608 again

server/http.go
我看到在`master`分支中，相关代码所实现的反向HTTP POST服务中请求的Method为`POST`，但在`dev`分支中它被修改为`GET`；
这项改动在[all: fix golangci-lint](https://github.com/Mrs4s/go-cqhttp/commit/656dc6b1035c8b6d40c4cc8c2565a15d7785ca50#diff-9dc8ed5b73297cf3c3d1d32cb36520c8f982a0194fad1e7b3fc521c5799e2023)中被引入，我认为它应当被修正为`POST`；
=> 将反向HTTP POST服务中请求的Method由GET修改为POST

global/fs.go
修复 FindFile 方法在 http 协议且无缓存的情况下返回空数据
fix #1831
=> fix: FindFile http return nil without cache

coolq/cqcode.go
如果通过go-cqhttp发送图片，再通过message_id 从数据库取出时，返回的message为空。
修复这个bug。
=> 修复取出消息时LocalImageElement缺失问题

.github/workflows/ci.yml
修复了 工件中未按预期 拼接二进制文件名 的问题。
原： ![image](https://user-images.githubusercontent.com/39934721/217624867-ebbe3b06-b95e-4fca-b1ec-e20d377984c4.png)
=> fix: BINARY_NAME wrong in ci action

cmd/gocq/main.go, global/terminal/doc.go, global/terminal/double_click.go, global/terminal/quick_edit.go, global/terminal/quick_edit_windows.go, global/terminal/vt100.go, global/terminal/vt100_windows.go, main.go
- 在解析参数之后，设置log之前禁用快速编辑并启用VT100
- 分离 Main 最开头的一段为 InitBase，一是为了可以让调包用户自定义参数，二是为了在二者之间插入快速编辑的逻辑，且如果用户不希望禁用快速编辑，可以方便地将其注释
=> feat: 禁用快速编辑&优化启动流程

cmd/gocq/login.go, cmd/gocq/main.go, internal/base/flag.go, modules/config/config.go, modules/config/default_config.yml
Add new function: register
update function: energy supports parameter uin now
=> update: support sign sever up to v1.1.3

coolq/api.go
解决以下问题：
当群组踢人时，该人不在群内，返回“群聊不存在”的BUG
https://github.com/Mrs4s/go-cqhttp/issues/1774#issue-1459854639
=> fix: group not found report (#2312)

cmd/gocq/login.go, cmd/gocq/main.go
#2303
The previous versions didn't wait for the sign server to start before performing instance registration. This issue has been fixed now.
It also supports the automatic registration feature of the current version of the sign server, thereby avoiding the situation where the program has to be restarted to re-register instances after the sign server crashes.
add functions in cmd/gocq/login.go:
The functions listenPort, dailPort, and waitForConnection use net.Dial to check if the sign server is running every five seconds. They will remain blocked until the sign server is started.
=> feat: add waitSignServer

internal/download/download.go
比如我的香橙派，因为性能很差，所以运行签名服务器的时候需要把超时改成50秒才能成功。（而M1瞬间就好了，我搞了半天不知道为什么同一个Dockerfile同一个架构会跑出不同的结果 :sob:  )
也许这个改成一个配置文件的项目会更好一点？不过改那么多对我来说比较难（）（）
=> 增加签名服务器请求超时时间

cmd/gocq/login.go, cmd/gocq/main.go, internal/base/flag.go, modules/config/config.go, modules/config/default_config.yml
考虑到公开的 signServer 可能并不想暴露给未知客户端，添加了 Bearer Authentication 进行一个简单的认证。
=> feat: add Bearer authentication to sign server requests

Dockerfile
=> :bug: 修复时区不是东八区的 BUG

.github/ISSUE_TEMPLATE/bug-report.yaml, .github/workflows/build_docker_image.yml, Dockerfile, coolq/api.go, docker-entrypoint.sh
* fix: group not found report (#2312)
解决以下问题：
当群组踢人时，该人不在群内，返回“群聊不存在”的BUG
https://github.com/Mrs4s/go-cqhttp/issues/1774#issue-1459854639
* Update bug-report.yaml (#2234)
* 更新docker action, 支持更多的平台 (#2217)
* Update build_docker_image.yml
* Update docker-entrypoint.sh
* Update build_docker_image.yml
* ✨ update docker action, more platforms are supported
---------
* :bug: 修复时区不是东八区的 BUG (#2212)
设置 TZ 环境变量需要先装`tzdata`这个包才会生效
* Update bug-report.yaml (#2126)
* Docker: support continuous params on CMD option (#1829)
now it supports usage like `docker run -it --rm go-cqhttp -faststart`
* make lint happy
---------
=> sync: dev to master (#2340)

internal/download/download.go
In response to the situation where the system buffer space becomes insufficient or the queue is full after a period of time for the program, the `http.Client.CloseIdleConnections()` method is utilized to close existing TCP connections.
=> fix #2368, which causes system lacked sufficient buffer space

cmd/gocq/login.go
解决了对于使用了强制 https 的 SignServer 在进行 TCP ping 时 错误的只截取了 host ，导致判定使用 80 端口而始终 ping 不通
的问题
TCP ping
http://xxx.com √
https://xxx.com:443 √
https://xxx.com ×
```bash
[2023-08-07 08:48:11] [INFO]: 使用服务器 https://xxx.com/ 进
行数据包签名
[2023-08-07 08:48:17] [WARNING]: 连接到签名服务器出现错误: 丢包4/4 时延9999ms
[2023-08-07 08:48:22] [WARNING]: 连接到签名服务器出现错误: 丢包4/4 时延9999ms
[2023-08-07 08:48:27] [WARNING]: 连接到签名服务器出现错误: 丢包4/4 时延9999ms
[2023-08-07 08:48:32] [WARNING]: 连接到签名服务器出现错误: 丢包4/4 时延9999ms
[2023-08-07 08:48:36] [FATAL]: 连接签名服务器失败
```
现在，它应该能正确的通过以上 TCP ping 的逻辑
同时，也确保了对于非 80/443 端口的 SignServer 服务器的 TCP ping 支持
```bash
[2023-08-07 08:58:53] [INFO]: 使用服务器 https://xxx.com/ 进
行数据包签名
[2023-08-07 08:59:00] [INFO]: 连接至签名服务器: https://xxx.com/
[2023-08-07 08:59:10] [INFO]: 注册QQ实例 10001成功: The QQ has already loaded an …
```
=> Fix: SignServer TCP ping for custom port

cmd/gocq/qsign.go
* fix: #2437 
* optimize: 当仅配置一个签名服务时不进行检查可用以及切换操作(仅有一个时也没地方切换)
* energy 出现decode 错误时打印出导致错误的具体数据内容，便于发现问题（）
* fix: 修复在因某些原因（如qsign崩溃）导致当前签名服务被标记为不可用后，可能导致刷新token时提示uin未注册或者qsign未初始化的问题
=> fix nil pointer dereference caused by nil 'cs'

cmd/gocq/main.go
ghproxy.com 已经被墙，根据其网页上的通知应当更换为二级域名 mirror.ghproxy.com，或考虑使用别的反代服务
=> fix: switch ghproxy.com to mirror.ghproxy.com
